### ISSUE TITLE
Testing URI problem.

### ISSUE THREAD

**Issue by ven7ura** [nilportugues/laravel5-jsonapi#29]
When I try to test with phpunit I get the following errors when I try to access the api:

```php
A request to [http://localhost/api/tags/1] failed. Received status code [500].

/Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithPages.php:168
/Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithPages.php:64
/Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithPages.php:45
/Users/ven7ura/Code/qp/tests/TagsTest.php:35
/Users/ven7ura/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:147
/Users/ven7ura/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:99

Caused by
exception 'InvalidArgumentException' with message 'The source URI string appears to be malformed' in /Users/ven7ura/Code/qp/vendor/zendframework/zend-diactoros/src/Uri.php:440
Stack trace:
#0 /Users/ven7ura/Code/qp/vendor/zendframework/zend-diactoros/src/Uri.php(104): Zend\Diactoros\Uri->parseUri('http://:/')
#1 /Users/ven7ura/Code/qp/vendor/zendframework/zend-diactoros/src/RequestTrait.php(80): Zend\Diactoros\Uri->__construct('http://:/')
#2 /Users/ven7ura/Code/qp/vendor/zendframework/zend-diactoros/src/ServerRequest.php(93): Zend\Diactoros\ServerRequest->initialize('http://:/', 'GET', Object(Zend\Diactoros\Stream), Array)
#3 /Users/ven7ura/Code/qp/vendor/symfony/psr-http-message-bridge/Factory/DiactorosFactory.php(62): Zend\Diactoros\ServerRequest->__construct(Array, Array, 'http://:/', 'GET', Object(Zend\Diactoros\Stream), Array)
#4 /Users/ven7ura/Code/qp/vendor/nilportugues/json-api/src/Http/Request/Request.php(32): Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory->createRequest(Object(Symfony\Component\HttpFoundation\Request))
#5 /Users/ven7ura/Code/qp/vendor/nilportugues/json-api/src/Http/Factory/RequestFactory.php(34): NilPortugues\Api\JsonApi\Http\Request\Request->__construct()
#6 /Users/ven7ura/Code/qp/vendor/nilportugues/laravel5-json-api/src/NilPortugues/Laravel5/JsonApi/Controller/JsonApiTrait.php(141): NilPortugues\Api\JsonApi\Http\Factory\RequestFactory::create()
#7 [internal function]: NilPortugues\Laravel5\JsonApi\Controller\JsonApiController->show('1')
#8 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(76): call_user_func_array(Array, Array)
#9 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('show', Array)
#10 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(Qpiensas\Http\Controllers\TagsController), Object(Illuminate\Routing\Route), 'show')
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Qpiensas\Http\Controllers\TagsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'show')
#17 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Qpiensas\\Http\\C...', 'show')
#18 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#19 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(52): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
#24 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(678): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(654): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#32 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#34 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /Users/ven7ura/Code/qp/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Clockwork\Support\Laravel\ClockworkMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#48 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#49 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(462): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#50 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithPages.php(62): Illuminate\Foundation\Testing\TestCase->call('GET', 'http://localhos...', Array, Array, Array)
#51 /Users/ven7ura/Code/qp/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithPages.php(45): Illuminate\Foundation\Testing\TestCase->makeRequest('GET', '/api/tags/1')
#52 /Users/ven7ura/Code/qp/tests/TagsTest.php(35): Illuminate\Foundation\Testing\TestCase->visit('/api/tags/1')
#53 [internal function]: TagsTest->testGetATag()
#54 /Users/ven7ura/Code/qp/vendor/phpunit/phpunit/src/Framework/TestCase.php(909): ReflectionMethod->invokeArgs(Object(TagsTest), Array)
#55 /Users/ven7ura/Code/qp/vendor/phpunit/phpunit/src/Framework/TestCase.php(768): PHPUnit_Framework_TestCase->runTest()
#56 /Users/ven7ura/Code/qp/vendor/phpunit/phpunit/src/Framework/TestResult.php(612): PHPUnit_Framework_TestCase->runBare()
#57 /Users/ven7ura/Code/qp/vendor/phpunit/phpunit/src/Framework/TestCase.php(724): PHPUnit_Framework_TestResult->run(Object(TagsTest))
#58 /Users/ven7ura/Code/qp/vendor/phpunit/phpunit/src/Framework/TestSuite.php(747): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#59 /Users/ven7ura/Code/qp/vendor/phpunit/phpunit/src/Framework/TestSuite.php(747): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#60 /Users/ven7ura/Code/qp/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(440): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#61 /Users/ven7ura/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(147): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#62 /Users/ven7ura/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(99): PHPUnit_TextUI_Command->run(Array, true)
#63 /Users/ven7ura/.composer/vendor/phpunit/phpunit/phpunit(36): PHPUnit_TextUI_Command::main()
#64 {main}
```

If I try to access with the browser or postman, I correctly get the data. So the problem is only when in a testing environment.

Any help will be appreciated.

**Comment by nilportugues** [comment]
This is actually a weird behaviour in Laravel. Hopefully this will fix your issues.

Try borrowing the call function in the tests: https://github.com/nilportugues/laravel5-jsonapi/blob/master/tests/NilPortugues/Laravel5/JsonApi/LaravelTestCase.php#L114-L125

**Comment by ven7ura** [comment]
Thanks, that resolves he issue.

**Comment by nilportugues** [comment]
@ven7ura great :smiley:

**Comment by marcogrueter** [comment]
Could you add this to the documentation? Or give me a hint in what form you'd like to have that, so I can supply a PR? I've just struggled with this for about an hour.

**Comment by nilportugues** [comment]
it just fails, because `php-cli` does not have the same values as `php-fpm` or `php-cgi`. I remember it took me quite a lot to figure as well. I'm sorry

I agree I should provide a base test file for this case... and add it to the documentation. Wanna help @marcogrueter ?

**Comment by marcogrueter** [comment]
Sure! Let me know what I can do.

**Comment by nilportugues** [comment]
@marcogrueter describe your solution here, create a JsonApiTestCase file and edit README explaining about this. :)
