### ISSUE TITLE
ErrorException DataObject:87 Undefined index: attributes

### ISSUE THREAD

**Issue by OskarD** [nilportugues/laravel5-jsonapi#59]
I don't know if I'm doing something wrong, but when I try to `POST` to a `store` action using Lumen, I get the following error:

```
lumen.ERROR: ErrorException: Undefined index: attributes in /home/vagrant/parties/api/vendor/nilportugues/json-api/src/Server/Data/DataObject.php:87
Stack trace:
#0 /home/vagrant/parties/api/vendor/nilportugues/json-api/src/Server/Data/DataObject.php(87): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Undefined index...', '/home/vagrant/p...', 87, Array)
#1 /home/vagrant/parties/api/vendor/nilportugues/json-api/src/Server/Data/DataObject.php(54): NilPortugues\Api\JsonApi\Server\Data\DataObject::missingCreationAttributes(Array, Object(NilPortugues\Laravel5\JsonApi\JsonApiSerializer))
#2 /home/vagrant/parties/api/vendor/nilportugues/json-api/src/Server/Actions/CreateResource.php(57): NilPortugues\Api\JsonApi\Server\Data\DataObject::assertPost(Array, Object(NilPortugues\Laravel5\JsonApi\JsonApiSerializer), 'App\\Party\\Party', Object(NilPortugues\Api\JsonApi\Server\Errors\ErrorBag))
#3 /home/vagrant/parties/api/vendor/nilportugues/laravel5-json-api/src/NilPortugues/Laravel5/JsonApi/Controller/JsonApiTrait.php(194): NilPortugues\Api\JsonApi\Server\Actions\CreateResource->get(Array, 'App\\Party\\Party', Object(Closure))
#4 [internal function]: NilPortugues\Laravel5\JsonApi\Controller\LumenJsonApiController->store(Object(Illuminate\Http\Request))
#5 /home/vagrant/parties/api/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#6 /home/vagrant/parties/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(586): Illuminate\Container\Container->call(Array, Array)
#7 /home/vagrant/parties/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(552): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#8 /home/vagrant/parties/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(526): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\v1\PartyController), 'store', Array)
#9 /home/vagrant/parties/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(494): Laravel\Lumen\Application->callControllerAction(Array)
#10 /home/vagrant/parties/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(479): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#11 /home/vagrant/parties/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(376): Laravel\Lumen\Application->handleFoundRoute(Array)
#12 /home/vagrant/parties/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(629): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#13 /home/vagrant/parties/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(382): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#14 /home/vagrant/parties/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(327): Laravel\Lumen\Application->dispatch(NULL)
#15 /home/vagrant/parties/api/public/index.php(28): Laravel\Lumen\Application->run()
#16 {main}  
``` 
I didn't get this before, and I don't have a custom action for the route

**Comment by OskarD** [comment]
Pretty sure I'm just stupid and broke my code so it doesn't send any JSON... Sorry ;)
